### ISSUE TITLE
Missing templates and Contribution guidelines in this repo

### ISSUE THREAD

**Issue by CCASTM** [STMicroelectronics/STM32CubeL0#1]
.github/ISSUES/Templates, .github/ISSUES/Templates, .github/Pull Request template
CONTRIBUTING , CODE_OF_CONDUCT
Regards
Christophe

**Comment by ALABSTM** [comment]
Hi @CCASTM,

Actually, this is due to the fact that these files have not been added and committed locally before the push. Now this has been corrected.
Thank you for having highlighted this point. I think the issue could be closed now.

Kind regards,
Ali

**Comment by CCASTM** [comment]
Ali,
Thank you for your prompt reply
Christophe
