### ISSUE TITLE
Add HAL_TIM_DMABurst_MultiWriteStart and HAL_TIM_DMABurst_MultiReadStart

### ISSUE THREAD

**Issue by statropy** [STMicroelectronics/STM32CubeL0#12]
Other repositories have been updated with `HAL_TIM_DMABurst_MultiWriteStart` and `HAL_TIM_DMABurst_MultiReadStart`. Is there any reason these functions can't be added for STM32CubeL0 also?

**Comment by ASELSTM** [comment]
Hi @statropy,

Actually, these functions has been added internally but not yet released. The fix will be published in the frame of a future publication. We cannot share a date for the moment. Stay tuned and thank you once more for your contribution and for your patience.

With regards,

**Comment by ASELSTM** [comment]
Hi @statropy, 

I hope you are fine. The issue you reported has been fixed in the frame of version **v1.12.0** of the STM32CubeL0 published recently on GitHub.

Thank you again for having reported.

With regards,
