### ISSUE TITLE
Outdated CMSIS header

### ISSUE THREAD

**Issue by LemonBoy** [STMicroelectronics/STM32CubeL0#30]
The `mpu_arm7.h` header shipped with the current version of the L0 (and possibly other) SDK has a bug that prevents the correct initialization of the MPU in a way that's hard to notice.
[This](https://github.com/ARM-software/CMSIS_5/commit/2ead2adffbffcaaef62253733e5f9f41f215973d#diff-e4bfba5228373d368ac2543d6e5bd4d0) commit shows that the problem with `ARM_MPU_RASR_EX` dropping important bits (it's missing the enable bit!) has been patched 5 years ago, I'd advise to backport this fix and/or update CMSIS as a whole.

**Comment by HBOSTM** [comment]
Hi @LemonBoy ,

A newer version of this library is available with several bugfixes [here](https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/Core/Include/mpu_armv7.h). Unfortunately, there is no plan in the near future to integrate any newer version of the library into this firmware. We will keep you informed, should there be any update in this plan.
In the meanwhile, you can easily integrate that newer version into your project by yourself, as it is backward compatible.
Please allow me to close this issue. Thank you for your comprehension and thank you for your report.

With regards,
