### ISSUE TITLE
32L0538DISCOVERY Missing project files

### ISSUE THREAD

**Issue by K2AAE** [STMicroelectronics/STM32CubeL0#4]
In STM32CubeL0/Projects/32L0538DISCOVERY/Demonstrations/ there are only project files for EWARM and MDK-ARM, no STM32CubeIDE (ST) or SW4STM32 (ac6) or TrueSTUDIO (Atollic/ST)

**Comment by ALABSTM** [comment]
Hi @K2AAE,

Thank you for having reported this point. It has been forwarded to our development team. Hopefully SW4STM32 project files will be provided in the frame of a future release.

Unfortunately, we cannot share a date for the moment. We count on your patience and comprehension. Take care and stay safe.

With regards,

**Comment by ALABSTM** [comment]
ST Internal Reference: 84588

**Comment by ALABSTM** [comment]
Hi @K2AAE,

I hope you are fine. Unfortunately, we could not address your request and we do apologize for the inconvenience. Indeed, this is a known limitation reported in the [release note](https://htmlpreview.github.io/?https://github.com/STMicroelectronics/STM32CubeL0/blob/master/Release_Notes.html) (as shown in the screenshot below).

According to our development teams, there is an issue particularly with the SW4STM32 project of the demo that could not be solved. Hence, choice has been made not to provide it.

We do apologize once again for the inconvenience and we thank you in advance for your comprehension.

With regards,
Ali

![image](https://user-images.githubusercontent.com/46019491/110312597-9781f380-8005-11eb-8dad-4688866ab4fd.png)
